management.endpoints.web.exposure.include=health
management.endpoint.shutdown.enabled=false

spring.mvc.servlet.path=/
server.servlet.context-path=/

server.error.whitelabel.enabled=true
server.error.include-exception=false
server.error.include-stacktrace=never

server.max-http-request-header-size=2MB
server.tomcat.max-http-form-post-size=2MB 
server.tomcat.connection-timeout=5s

spl.error.exception-handler.enabled=true
spl.error.exception-handler.auditlog=true

spl.security.generated-dev-password.enabled=false

spl.security.http-firewall.enabled=false
spl.security.http-firewall.regex=[\\\\p{IsAssigned}&&[[^\\\\p{IsControl}]||\\\\t]]*

spl.security.authentication.anonymous.enabled=false
spl.security.authentication.anonymous.uri-matchers=/favicon.ico

spl.security.authentication.propagator.enabled=false
spl.security.authentication.propagator.uri-matchers=/**

spl.security.authentication.springline.enabled=false
spl.security.authentication.springline.uri-matchers=/**
spl.security.authentication.springline.header.username=x-springline-username
spl.security.authentication.springline.header.authchannel=x-springline-authchannel
spl.security.authentication.springline.header.authmethod=x-springline-authmethod
spl.security.authentication.springline.header.authstrength=x-springline-authstrength
spl.security.authentication.springline.header.role=x-springline-role
spl.security.authentication.springline.header.firstname=x-springline-firstname
spl.security.authentication.springline.header.lastname=x-springline-lastname
spl.security.authentication.springline.header.realvirtual=x-springline-realvirtual
spl.security.authentication.springline.header.fiscalcode=x-springline-fiscalcode
spl.security.authentication.springline.header.email=x-springline-email
spl.security.authentication.springline.header.credential=x-springline-credential
spl.security.authentication.springline.header.appname=x-springline-appname

spl.security.authentication.samweb.enabled=false
spl.security.authentication.samweb.uri-matchers=/**
spl.security.authentication.samweb.header.activcred=activcred
spl.security.authentication.samweb.header.uid=uid
spl.security.authentication.samweb.header.token=token
spl.security.authentication.samweb.header.tokenssodn=token_ssodn
spl.security.authentication.samweb.header.ssourllogout=saml_attribute_ssourllogout

spl.security.authentication.idpc.enabled=false
spl.security.authentication.idpc.uri-matchers=/**
spl.security.authentication.idpc.header.codicefiscale=saml_attribute_codicefiscale
spl.security.authentication.idpc.header.nome=saml_attribute_nome
spl.security.authentication.idpc.header.cognome=saml_attribute_cognome
spl.security.authentication.idpc.header.cartareale=saml_attribute_cns_carta_reale
spl.security.authentication.idpc.header.tipoautenticazione=saml_attribute_tipoautenticazione
spl.security.authentication.idpc.header.livello-verifica=saml_attribute_livelloverifica
spl.security.authentication.idpc.header.email-address=saml_attribute_emailaddress
spl.security.authentication.idpc.header.ssourllogout=saml_attribute_ssourllogout
spl.security.authentication.idpc.header.nomeutente=saml_attribute_nomeutente
spl.security.authentication.idpc.header.sesso=saml_attribute_sesso
spl.security.authentication.idpc.header.datanascita=saml_attribute_datanascita
spl.security.authentication.idpc.header.luogonascita=saml_attribute_luogonascita
spl.security.authentication.idpc.header.provincianascita=saml_attribute_provincianascita
spl.security.authentication.idpc.header.statonascita=saml_attribute_statonascita
spl.security.authentication.idpc.header.cellulare=saml_attribute_cellulare
spl.security.authentication.idpc.header.ragionesociale=saml_attribute_ragionesociale
spl.security.authentication.idpc.header.sedelegale=saml_attribute_sedelegale
spl.security.authentication.idpc.header.partitaiva=saml_attribute_partitaiva
spl.security.authentication.idpc.header.docidentita=saml_attribute_docidentita
spl.security.authentication.idpc.header.scaddocidentita=saml_attribute_scaddocidentita
spl.security.authentication.idpc.header.domiciliofisico=saml_attribute_domiciliofisico
spl.security.authentication.idpc.header.domiciliodigitale=saml_attribute_domiciliodigitale
spl.security.authentication.idpc.header.cnsissuer=saml_attribute_cns_issuer
spl.security.authentication.idpc.header.cnssubject=saml_attribute_cns_subject
spl.security.authentication.idpc.header.originedatiutente=saml_attribute_originedatiutente
spl.security.authentication.idpc.header.idcomuneregistrazione=saml_attribute_idcomuneregistrazione
spl.security.authentication.idpc.header.dataultimologin=data_ultimo_login
spl.security.authentication.idpc.header.oraultimologin=ora_ultimo_login
spl.security.authentication.idpc.header.indirizzoipcorrente=indirizzo_ip_corrente
spl.security.authentication.idpc.header.indirizzoipprecedente=indirizzo_ip_precedente
spl.security.authentication.idpc.header.tipospid=saml_attribute_tipo_spid
spl.security.authentication.idpc.header.servizioultimologin=saml_attribute_servizio_ultimo_login
spl.security.authentication.idpc.header.capdomiciliofisico=saml_attribute_capdomiciliofisico
spl.security.authentication.idpc.header.comunedomiciliofisico=saml_attribute_comunedomiciliofisico
spl.security.authentication.idpc.header.provinciadomiciliofisico=saml_attribute_provinciadomiciliofisico
spl.security.authentication.idpc.header.nazionedomiciliofisico=saml_attribute_nazionedomiciliofisico
spl.security.authentication.idpc.header.idpultimologin=saml_attribute_idp_ultimo_login
spl.security.authentication.idpc.header.organizzazione=organizzazione
spl.security.authentication.idpc.header.matricola=matricola
spl.security.authentication.idpc.header.enteappartenenza=enteappartenenza
spl.security.authentication.idpc.header.descrizioneente=descrizioneente
spl.security.authentication.idpc.header.statolavorativo=statolavorativo

spl.security.authentication.iam.enabled=false
spl.security.authentication.iam.uri-matchers=/**
spl.security.authentication.iam.header.codicefiscale=http_codicefiscale
spl.security.authentication.iam.header.matricola=http_matricola
spl.security.authentication.iam.header.nome=http_nome
spl.security.authentication.iam.header.cognome=http_cognome
spl.security.authentication.iam.header.email=http_email

spl.security.authentication.apimanager.enabled=false
spl.security.authentication.apimanager.uri-matchers=/**
spl.security.authentication.apimanager.header.assertion=x-jwt-assertion
spl.security.authentication.apimanager.header.uid=uid
spl.security.authentication.apimanager.header.token=token
spl.security.authentication.apimanager.header.tokenssodn=token_ssodn
spl.security.authentication.apimanager.header.ssourllogout=saml_attribute_ssourllogout
spl.security.authentication.apimanager.header.activcred=activcred

spl.security.authentication.jwt.enabled=false
spl.security.authentication.jwt.uri-matchers=/**
spl.security.authentication.jwt.header.authorization-bearer=authorization

spl.security.authentication.jwt.header.enabled=true
spl.security.authentication.jwt.cookie.enabled=false
spl.security.authentication.jwt.cookie.name=springline2Token

spl.security.jwt.cypher-secret=
spl.security.jwt.token-validity=1800

spl.datasource.logging.execution-time=false
spl.datasource.reale-virtuale=false

spl.open-api.configuration=true
spl.open-api.info.title=
spl.open-api.info.description=
spl.open-api.info.summary=
spl.open-api.info.term-of-service=
spl.open-api.info.term-of-service-url=
spl.open-api.info.version=
spl.open-api.info.contact.name=
spl.open-api.info.contact.url=
spl.open-api.info.contact.email=
spl.open-api.info.license.name=
spl.open-api.info.license.url=
spl.open-api.info.license.identifier=
spl.open-api.authorize.samweb=false
spl.open-api.authorize.apimanager=false
spl.open-api.authorize.iam=false
spl.open-api.authorize.idpc=false

spl.http.logging.mon.enabled=true
spl.http.logging.mon.uri-matchers=/**
spl.http.logging.mon.excluded-uri-matchers=/favicon.ico
spl.http.logging.app.enabled=false
spl.http.logging.app.uri-matchers=/**
spl.http.logging.app.excluded-uri-matchers=/favicon.ico
spl.http.logging.app.excluded-content-types=application/x-www-form-urlencoded,multipart/form-data
spl.http.logging.app.body-max-length=1048576

spl.jms.listener.enabled=true
spl.jms.logging.mon.enabled=true
spl.jms.logging.mon.destination-matchers=**
spl.jms.logging.mon.excluded-destination-matchers=
spl.jms.logging.app.enabled=false
spl.jms.logging.app.destination-matchers=**
spl.jms.logging.app.excluded-destination-matchers=
spl.jms.logging.app.body-max-length=1048576

spl.client-rest.autoconfiguration.enabled=true

spl.client-rest.logging.mon.enabled=true
spl.client-rest.logging.mon.uri-matchers=/**
spl.client-rest.logging.mon.excluded-uri-matchers=
spl.client-rest.logging.app.enabled=false
spl.client-rest.logging.app.uri-matchers=/**
spl.client-rest.logging.app.excluded-uri-matchers=
spl.client-rest.logging.app.excluded-content-types=
spl.client-rest.logging.app.body-max-length=1048576

spl.client-rest.propagation.springline2.enabled=false
spl.client-rest.propagation.springline2.uri-matchers=
spl.client-rest.propagation.springline2.excluded-uri-matchers=

spl.client-rest.propagation.springline.enabled=false
spl.client-rest.propagation.springline.uri-matchers=
spl.client-rest.propagation.springline.excluded-uri-matchers=
spl.client-rest.propagation.springline.header.username=x-springline-username
spl.client-rest.propagation.springline.header.authchannel=x-springline-authchannel
spl.client-rest.propagation.springline.header.authmethod=x-springline-authmethod
spl.client-rest.propagation.springline.header.authstrength=x-springline-authstrength
spl.client-rest.propagation.springline.header.role=x-springline-role
spl.client-rest.propagation.springline.header.firstname=x-springline-firstname
spl.client-rest.propagation.springline.header.lastname=x-springline-lastname
spl.client-rest.propagation.springline.header.realvirtual=x-springline-realvirtual
spl.client-rest.propagation.springline.header.fiscalcode=x-springline-fiscalcode
spl.client-rest.propagation.springline.header.email=x-springline-email
spl.client-rest.propagation.springline.header.credential=x-springline-credential
spl.client-rest.propagation.springline.header.appname=x-springline-appname

spl.client-rest.retry.uri-matchers=/**
spl.client-rest.retry.excluded-uri-matchers=
spl.client-rest.retry.enabled=false
spl.client-rest.retry.max-retries=3
spl.client-rest.retry.with-timeout=0
spl.client-rest.retry.fixed-backoff=0

spl.client-jms.logging.mon.enabled=true
spl.client-jms.logging.mon.destination-matchers=**
spl.client-jms.logging.mon.excluded-destination-matchers=
spl.client-jms.logging.app.enabled=false
spl.client-jms.logging.app.destination-matchers=**
spl.client-jms.logging.app.excluded-destination-matchers=
spl.client-jms.logging.app.body-max-length=1048576

spl.client-ws.autoconfiguration.enabled:true

spl.client-ws.propagation.siss.enabled=false
spl.client-ws.propagation.siss.method-matchers=
spl.client-ws.propagation.siss.excluded-method-matchers=
spl.client-ws.propagation.siss.header.userid=userid
spl.client-ws.propagation.siss.header.role=role
spl.client-ws.propagation.siss.header.activcred=activcred
spl.client-ws.propagation.siss.header.uid=uid
spl.client-ws.propagation.siss.header.token=token
spl.client-ws.propagation.siss.header.tokenssodn=token_ssodn
spl.client-ws.propagation.siss.header.ssourllogout=saml_attribute_ssourllogout

spl.client-ws.logging.mon.enabled=true
spl.client-ws.logging.mon.method-matchers=**
spl.client-ws.logging.mon.excluded-method-matchers=
spl.client-ws.logging.app.enabled=false
spl.client-ws.logging.app.method-matchers=**
spl.client-ws.logging.app.excluded-method-matchers=
spl.client-ws.logging.app.body-max-length=1048576

