spring.cloud.config.enabled=false
spring.cloud.bootstrap.enabled=true

logging.config=classpath:logback-springline2.xml
logging.file.path=logs
logging.level.root=INFO
logging.level.org.springframework.core.LocalVariableTableParameterNameDiscoverer=ERROR

spring.cloud.consul.enabled=false
spring.cloud.consul.discovery.enabled=false
spring.cloud.consul.service-registry.enabled=false      
spring.cloud.consul.config.enabled=true
spring.cloud.consul.config.prefix=config-server
spring.cloud.consul.config.data-key=application.yml
spring.cloud.consul.config.format=YAML

spl.logging.encrypt.keyStore.location=
spl.logging.encrypt.keyStore.password=
spl.logging.encrypt.keyStore.type=
spl.logging.encrypt.keyStore.alias=

spl.conjur.enabled=true
spl.conjur.appliance-url=
spl.conjur.account=
spl.conjur.authn.login=
spl.conjur.authn.api-key=
spl.conjur.authn.url=
spl.conjur.authn.token-file=
spl.conjur.tls-ca-path=
spl.conjur.cache=false
