-- =============================================================================
-- Script 006: Dati di esempio per mygov_ente_config_pu (ambiente DEV)
-- =============================================================================
-- Inserisce una configurazione PU di esempio per un ente presente in mygov_ente.
--
-- ATTENZIONE:
--   - Sostituire i valori <CLIENT_ID> e <CLIENT_SECRET> con le credenziali reali
--     rilasciate dalla Piattaforma Unitaria per ciascun ente.
--   - Verificare che il codice IPA sia presente nella tabella mygov_ente.
--   - Non eseguire questo script in produzione senza aver sostituito i valori.
-- =============================================================================

-- Esempio: ente con configurazione PU attiva (usa flusso OAuth2)
-- INSERT INTO mygov_ente_config_pu (codice_ipa_ente, client_id, client_secret, attivo)
-- VALUES (
--     'R_LOMBARDIA',                          -- cod_ipa_ente dell'ente in mygov_ente
--     'SELC_99999000013SIL_RegLomb2',         -- client_id assegnato dalla PU
--     'il_secret_qui',                         -- client_secret assegnato dalla PU
--     TRUE
-- );

-- Esempio: ente con configurazione PU disattivata (usa flusso legacy)
-- INSERT INTO mygov_ente_config_pu (codice_ipa_ente, client_id, client_secret, attivo)
-- VALUES (
--     'C_F205',                               -- cod_ipa_ente dell'ente in mygov_ente
--     'SELC_client_id_ente_legacy',
--     'secret_legacy',
--     FALSE                                   -- attivo=FALSE -> usa flusso legacy
-- );

-- Per verificare la configurazione:
-- SELECT e.cod_ipa_ente, e.de_nome_ente, p.client_id, p.attivo
-- FROM mygov_ente e
-- LEFT JOIN mygov_ente_config_pu p ON p.codice_ipa_ente = e.cod_ipa_ente
-- ORDER BY e.cod_ipa_ente;
