spring:
  datasource:
    url: jdbc:oracle:thin:@<INSERIRE IP>:<INSERIRE PORT>:<INSERIRE SID>
    username: <INSERIRE USER>
    password: <INSERIRE PASSWORD>
    hikari:
      minimumIdle: 1
      maximumPoolSize: 5
      idleTimeout: 30000
      maxLifetime: 60000
  
server:
   port: 8443
   ssl:
      keyStore: certs/lispa.local.p12
      keyStoreType: PKCS12
      keyAlias: lispa.local
      keyStorePassword: <INSERIRE PASSWORD>
      enabled: true
      enabledProtocols: TLSv1.2
      protocol: TLS      

spl:
  http:
    logging:
      app.enabled: true
  client-rest:
    logging:
      app.enabled: true
  client-ws:
    logging:
      app.enabled: true

  open-api:
    authorize:
      idpc: true

  security:
    jwt:
      cypher-secret: <INSERIRE SECRET TOKEN>
      
uploadLocation: /repository

url:
  test_error: https://localhost.lispa.local:8443/api/test_error
  test_ok: https://localhost.lispa.local:8443/api/test_ok